steps:
- name: 'gcr.io/$_PROJECT_ID/helm'
  args: 
    - upgrade
    - -i
    - helloworld
    - ./helm-chart/helloworld
    - -f 
    - ./helm-chart/helloworld/values.yaml
  
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloudbuild'

options:
  logging: CLOUD_LOGGING_ONLY
