steps:
- name: 'gcr.io/$_PROJECT_ID/helm'
  args: 
    - upgrade
    - install
    - kanban -f postgres.yaml 
   
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloudbuild'

options:
  logging: CLOUD_LOGGING_ONLY
####
